name: lemper-stack
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
#      - '!master'   # excludes master
  pull_request:
    branches: 
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # Prepare testing environment
      - name: Prepare testing environment
        run: |
          cp .env.dist .env
          sed -i "s/ENVIRONMENT=\"production\"/ENVIRONMENT=\"development\"/g" .env
          sed -i "s/SERVER_HOSTNAME=\"\"/SERVER_HOSTNAME=\"travis-ci.masedi.net\"/g" .env
          sed -i "s/SERVER_IP=\"\"/SERVER_IP=\"127.0.0.1\"/g" .env
          sed -i "s/AUTO_INSTALL=false/AUTO_INSTALL=true/g" .env
          sed -i "s/AUTO_REMOVE=false/AUTO_REMOVE=true/g" .env
          sed -i "s/FORCE_REMOVE=false/FORCE_REMOVE=true/g" .env
          sed -i "s/LEMPER_ADMIN_EMAIL=\"mail@example.com\"/LEMPER_ADMIN_EMAIL=\"me@masedi.net\"/g" .env
          sed -i "s/PHP_VERSION=\"7.4\"/PHP_VERSION=\"7.4\"/g" .env
          sed -i "s/INSTALL_PHP_LOADER=false/INSTALL_PHP_LOADER=true/g" .env
          sed -i "s/PHP_LOADER=\"none\"/PHP_LOADER=\"ioncube\"/g" .env
          sed -i "s/PHP_IMAGEMAGICK_INSTALLER=\"repo\"/PHP_IMAGEMAGICK_INSTALLER=\"source\"/g" .env
          sed -i "s/INSTALL_MAILER=true/INSTALL_MAILER=false/g" .env
          sed -i "s/INSTALL_SPFDKIM=true/INSTALL_SPFDKIM=false/g" .env
          sed -i "s/SENDER_DOMAIN=\"example.com\"/SENDER_DOMAIN=\"localhost.localhost\"/g" .env
          sed -i "s/INSTALL_FAIL2BAN=false/INSTALL_FAIL2BAN=true/g" .env
      # Install Dependencies
      - name: Install testing dependencies
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -qq -y bash curl
          sudo curl -s -o /usr/local/bin/shunit2 https://raw.githubusercontent.com/kward/shunit2/master/shunit2
          sudo chmod a+x /usr/local/bin/shunit2
          sudo curl -s -o shellcheck-v0.7.2.linux.x86_64.tar.xz https://github.com/koalaman/shellcheck/releases/download/v0.7.2/shellcheck-v0.7.2.linux.x86_64.tar.xz
          sudo tar -xf shellcheck-v0.7.2.linux.x86_64.tar.xz
          sudo mv shellcheck-v0.7.2/shellcheck /usr/local/bin/
          sudo chmod a+x /usr/local/bin/shellcheck
      # Shellcheck Tests
      - name: Run shellcheck testing
        env:
          TERM: xterm-256color
        run: |
          shellcheck -s bash -x install.sh
          shellcheck -s bash -x remove.sh
          shellcheck -s bash -x lib/lemper-*.sh
          shellcheck -s bash -x scripts/cleanup_server.sh
          shellcheck -s bash -x scripts/helper.sh
          shellcheck -s bash -x scripts/install_*.sh
          shellcheck -s bash -x scripts/remove_*.sh
          shellcheck -s bash -x scripts/secure_server.sh
      # Simple Unit Tests
      - name: Run unit testing
        env:
          TERM: xterm-256color
        run: |
          sudo bash scripts/cleanup_server.sh
          sudo bash scripts/install_dependencies.sh
          sudo bash shunit2/run_test.sh
